# Generated by Django 5.0.6 on 2024-06-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingparameters',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('executing', 'запущена'), ('finished', 'закончена успешно'), ('error', 'законечена с ошибками')], default='created', max_length=15, verbose_name='Статус рассылки'),
        ),
    ]
