# Generated by Django 5.0.6 on 2024-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingparameters_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingparameters',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='mailingparameters',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('is_active', 'запущена'), ('finished', 'закончена успешно'), ('finished_date', 'закончена при проверке срока'), ('finished_error', 'законечена с ошибками')], default='created', max_length=15, verbose_name='Статус рассылки'),
        ),
    ]
