# Generated by Django 5.0.6 on 2024-06-29 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_mailingparameters_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingparameters',
            name='next_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 15, 12, 52, 45047, tzinfo=datetime.timezone.utc), verbose_name='дата следующей рассылки'),
        ),
    ]
