# Generated by Django 5.0.6 on 2024-06-30 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailingparameters_next_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingparameters',
            name='interval',
            field=models.CharField(choices=[('per_day', 'раз в день'), ('per_week', 'раз в неделю'), ('per_month', 'раз в месяц')], default='once', max_length=50, verbose_name='интервал рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingparameters',
            name='next_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 52, 42, 9622, tzinfo=datetime.timezone.utc), verbose_name='дата следующей рассылки'),
        ),
    ]
