# Generated by Django 4.2.2 on 2024-06-30 21:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0007_alter_mailingparameters_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingparameters',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cоздатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cоздатель'),
        ),
        migrations.AlterField(
            model_name='mailingparameters',
            name='next_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 21, 32, 18, 903161, tzinfo=datetime.timezone.utc), verbose_name='дата следующей рассылки'),
        ),
    ]
