# Generated by Django 4.2.2 on 2024-07-01 11:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_mailingparameters_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingparameters',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 11, 2, 37, 498429, tzinfo=datetime.timezone.utc), verbose_name='конец рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingparameters',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата следующей рассылки'),
        ),
    ]
