# Generated by Django 4.2.2 on 2024-07-01 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailingparameters_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingparameters',
            options={'permissions': [('change_status', 'Can change status')], 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылок'},
        ),
        migrations.AlterField(
            model_name='mailingparameters',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 33, 48, 818966, tzinfo=datetime.timezone.utc), verbose_name='конец рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingparameters',
            name='status',
            field=models.CharField(choices=[('not_active', 'не активна'), ('is_active', 'запущена'), ('finished', 'закончена успешно'), ('finished_date', 'закончена по сроку'), ('finished_error', 'законечена с ошибками')], default='not_active', max_length=50, verbose_name='Статус рассылки'),
        ),
    ]
