# Generated by Django 4.2.2 on 2024-07-01 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailingparameters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingparameters',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 23, 14, 51, 523919, tzinfo=datetime.timezone.utc), verbose_name='конец рассылки'),
        ),
    ]
